// Generated by TMBtools: do not edit by hand

//#define TMB_LIB_INIT R_init_tmbGMACS_TMBExports
#ifdef TMB_LIB_INIT
#undef TMB_LIB_INIT
#endif

#include <TMB.hpp>
#define TMB_HPP_DEFINED
#include "GMACS.hpp"
//#include "test_gmacs.hpp"

template<class Type>
Type objective_function<Type>::operator() () {
  DATA_STRING(model);
  if(model == "GMACS") {
    return GMACS(this);
  } else if(model == "test_gmacs") {
//    return test_gmacs(this);
  } else {
    Rf_error("Unknown model.");
  }
  return 0;
}
