// Generated by TMBtools: do not edit by hand

#define TMB_LIB_INIT R_init_tmbGMACS_TMBExports
#include <TMB.hpp>
#include "gmacs.hpp"

template<class Type>
Type objective_function<Type>::operator() () {
  DATA_STRING(model);
  if(model == "gmacs") {
    return gmacs(this);
  } else {
    Rf_error("Unknown model.");
  }
  return 0;
}
